/**
 * 即梦图像生成API类型定义
 * 基于官方文档：https://www.volcengine.com/docs/85621/1616429
 */

export interface JimengConfig {
  accessKey: string;
  secretKey: string;
  endpoint?: string;
  region?: string;
  service?: string;
}

// 提交任务请求参数
export interface ImageGenerationRequest {
  // 必选参数
  req_key: string; // 算法名称，取固定值为jimeng_t2i_v30
  prompt: string; // 用于生成图像的提示词，中英文均可输入。建议长度<=120字符，最长不超过800字符

  // 可选参数
  use_pre_llm?: boolean; // 开启文本扩写，会针对输入prompt进行扩写优化，如果输入prompt较短建议开启，如果输入prompt较长建议关闭 默认值：true
  seed?: number; // 随机种子，作为确定扩散初始状态的基础，默认-1（随机）。若随机种子为相同正整数且其他参数均一致，则生成图片极大概率效果一致 默认值：-1
  width?: number; // 生成图像宽度，系统默认生成1328 * 1328的图像；支持自定义生成图像宽高，宽高比在1:3到3:1之间，长度在[512, 2048]之间
  height?: number; // 生成图像高度，需同时传width和height才会生效
}

// 提交任务返回参数
export interface ImageGenerationResponse {
  code: string;
  data: {
    task_id: string; // 任务ID，用于查询结果
  };
  message: string;
  request_id: string;
  status: string;
  time_elapsed: string;
}

// 查询任务请求参数
export interface TaskQueryRequest {
  req_key: string; // 服务标识，取固定值: jimeng_t2i_v30
  task_id: string; // 任务ID，此字段的取值为提交任务接口的返回
  req_json?: string; // json序列化后的字符串，支持水印配置和是否以图片链接形式返回
}

// 水印配置
export interface LogoInfo {
  add_logo?: boolean; // 是否添加水印。True为添加，False不添加。默认不添加
  position?: number; // 水印的位置，取值如下：0-右下角 1-左下角 2-左上角 3-右上角 默认0
  language?: number; // 水印的语言，取值如下：0-中文（AI生成） 1-英文（Generated by AI） 默认0
  opacity?: number; // 水印的不透明度，取值范围0-1，1表示完全不透明，默认0.3
  logo_text_content?: string; // 明水印自定义内容
}

// 查询任务配置
export interface TaskQueryConfig {
  return_url?: boolean; // 输出是否返回图片链接（链接有效期为24小时）
  logo_info?: LogoInfo; // 水印信息
}

// 查询任务返回参数
export interface TaskQueryResponse {
  code: string;
  data: {
    binary_data_base64: string[] | null; // 返回图片的base64数组
    image_urls: string[] | null; // 返回图片的url数组
    status: 'in_queue' | 'generating' | 'done' | 'not_found' | 'expired'; // 任务执行状态
  };
  message: string;
  request_id: string;
  status: string;
  time_elapsed: string;
}

// 错误码定义
export interface JimengError {
  HttpCode: number;
  错误码: string;
  错误消息: string;
  描述: string;
  是否需要重试: string;
}

// API常量
export const JIMENG_API_CONSTANTS = {
  // 固定值
  REQ_KEY: 'jimeng_t2i_v30',
  ACTION_SUBMIT: 'CVSync2AsyncSubmitTask',
  ACTION_QUERY: 'CVSync2AsyncGetResult',
  VERSION: '2022-08-31',

  // 默认配置
  DEFAULT_REGION: 'cn-north-1',
  DEFAULT_SERVICE: 'cv',
  DEFAULT_ENDPOINT: 'https://visual.volcengineapi.com',

  // 推荐尺寸
  RECOMMENDED_SIZES: {
    STANDARD_1K: {
      '1:1': { width: 1328, height: 1328 },
      '4:3': { width: 1472, height: 1104 },
      '3:2': { width: 1584, height: 1056 },
      '16:9': { width: 1664, height: 936 },
      '21:9': { width: 2016, height: 864 },
    },
    HD_2K: {
      '1:1': { width: 2048, height: 2048 },
      '4:3': { width: 2304, height: 1728 },
      '3:2': { width: 2496, height: 1664 },
      '16:9': { width: 2560, height: 1440 },
      '21:9': { width: 3024, height: 1296 },
    },
  },

  // 水印位置
  WATERMARK_POSITIONS: {
    BOTTOM_RIGHT: 0, // 右下角
    BOTTOM_LEFT: 1, // 左下角
    TOP_LEFT: 2, // 左上角
    TOP_RIGHT: 3, // 右上角
  },

  // 水印语言
  WATERMARK_LANGUAGES: {
    CHINESE: 0, // 中文（AI生成）
    ENGLISH: 1, // 英文（Generated by AI）
  },
} as const;
